[git]
tag_prefix = "v"         # Prefix for semantic tags

[output]
file   = "CHANGELOG.md"
format = "MD"            # Markdown

[sections]
"ğŸš€ Added"      = ["feat"]
"ğŸ› Fixed"      = ["fix"]
"ğŸ§° Changed"    = ["perf"]
"âš ï¸ Deprecated" = ["chore(deprecate)"]
"ğŸš« Removed"    = ["feat!", "BREAKING CHANGE"]
"ğŸ”’ Security"   = ["fix(security)", "security"]