# yaml-language-server: $schema=settings.schema.yaml
$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
db_url: null
accounts:
  # Get from https://api.innohassle.ru/accounts/v0/tokens/generate-service-token?sub=workshops-local-dev&scopes=users&only_for_me=true
  api_jwt_token: null
minio:
  endpoint: minio:9000
  access_key: "minioadmin"
  secret_key: "password"
api_key: null
superadmin_emails: [ "n.surname@email.example" ]
